package gg.cloud9.euls.constants;

import com.google.common.collect.ImmutableBiMap;
import com.google.common.collect.ImmutableMap;

public class DotaGameConstants {
    public static final ImmutableBiMap<Integer, String> TEAM = ImmutableBiMap.<Integer, String>builder()
            .put(2, "Radiant")
            .put(3, "Dire")
            .put(5, "Spectator")
            .build();

    public static final ImmutableMap<String, Integer> TEAM_REVERSE = TEAM.inverse();

    // TODO: Add TerrorBlade, Phoenix
    public static final ImmutableBiMap<Integer, String> HEROES = ImmutableBiMap.<Integer, String>builder()
            .put(0, "None")
            .put(1, "Anti-Mage")
            .put(2, "Axe")
            .put(3, "Bane")
            .put(4, "Bloodseeker")
            .put(5, "Crystal Maiden")
            .put(6, "Drow Ranger")
            .put(7, "Earthshaker")
            .put(8, "Juggernaut")
            .put(9, "Mirana")
            .put(10, "Morphling")
            .put(11, "Shadow Fiend")
            .put(12, "Phantom Lancer")
            .put(13, "Puck")
            .put(14, "Pudge")
            .put(15, "Razor")
            .put(16, "Sand King")
            .put(17, "Storm Spirit")
            .put(18, "Sven")
            .put(19, "Tiny")
            .put(20, "Vengeful Spirit")
            .put(21, "Windranger")
            .put(22, "Zeus")
            .put(23, "Kunkka")
            .put(25, "Lina")
            .put(26, "Lion")
            .put(27, "Shadow Shaman")
            .put(28, "Slardar")
            .put(29, "Tidehunter")
            .put(30, "Witch Doctor")
            .put(31, "Lich")
            .put(32, "Riki")
            .put(33, "Enigma")
            .put(34, "Tinker")
            .put(35, "Sniper")
            .put(36, "Necrophos")
            .put(37, "Warlock")
            .put(38, "Beastmaster")
            .put(39, "Queen of Pain")
            .put(40, "Venomancer")
            .put(41, "Faceless Void")
            .put(42, "Wraith King")
            .put(43, "Death Prophet")
            .put(44, "Phantom Assassin")
            .put(45, "Pugna")
            .put(46, "Templar Assassin")
            .put(47, "Viper")
            .put(48, "Luna")
            .put(49, "Dragon Knight")
            .put(50, "Dazzle")
            .put(51, "Clockwerk")
            .put(52, "Leshrac")
            .put(53, "Nature's Prophet")
            .put(54, "Life Stealer")
            .put(55, "Dark Seer")
            .put(56, "Clinkz")
            .put(57, "Omniknight")
            .put(58, "Enchantress")
            .put(59, "Huskar")
            .put(60, "Night Stalker")
            .put(61, "Broodmother")
            .put(62, "Bounty Hunter")
            .put(63, "Weaver")
            .put(64, "Jakiro")
            .put(65, "Batrider")
            .put(66, "Chen")
            .put(67, "Spectre")
            .put(68, "Ancient Apparition")
            .put(69, "Doom Bringer")
            .put(70, "Ursa")
            .put(71, "Spirit Breaker")
            .put(72, "Gyrocopter")
            .put(73, "Alchemist")
            .put(74, "Invoker")
            .put(75, "Silencer")
            .put(76, "Outworld Devourer")
            .put(77, "Lycan")
            .put(78, "Brewmaster")
            .put(79, "Shadow Demon")
            .put(80, "Lone Druid")
            .put(81, "Chaos Knight")
            .put(82, "Meepo")
            .put(83, "Treant Protector")
            .put(84, "Ogre Magi")
            .put(85, "Undying")
            .put(86, "Rubick")
            .put(87, "Disruptor")
            .put(88, "Nyx Assassin")
            .put(89, "Naga Siren")
            .put(90, "Keeper of the Light")
            .put(91, "Io")
            .put(92, "Visage")
            .put(93, "Slark")
            .put(94, "Medusa")
            .put(95, "Troll Warlord")
            .put(96, "Centaur Warrunner")
            .put(97, "Magnus")
            .put(98, "Timbersaw")
            .put(99, "Bristleback")
            .put(100, "Tusk")
            .put(101, "Skywrath Mage")
            .put(102, "Abaddon")
            .put(103, "Elder Titan")
            .put(104, "Legion Commander")
            .put(106, "Ember Spirit")
            .put(107, "Earth Spirit")
            .put(108, "Abyssal Underlord")
            .build();

    // TODO: Add TerrorBlade, Phoenix, Earth Spirit, Ember Spirit, and Abyssal Underlord
    public static final ImmutableBiMap<Integer, String> HEROES_INTERNAL_NAME = ImmutableBiMap.<Integer, String>builder()
            .put(1, "AntiMage")
            .put(2, "Axe")
            .put(3, "Bane")
            .put(4, "Bloodseeker")
            .put(5, "CrystalMaiden")
            .put(6, "DrowRanger")
            .put(7, "Earthshaker")
            .put(8, "Juggernaut")
            .put(9, "Mirana")
            .put(10, "Morphling")
            .put(11, "Nevermore")
            .put(12, "PhantomLancer")
            .put(13, "Puck")
            .put(14, "Pudge")
            .put(15, "Razor")
            .put(16, "SandKing")
            .put(17, "StormSpirit")
            .put(18, "Sven")
            .put(19, "Tiny")
            .put(20, "VengefulSpirit")
            .put(21, "Windrunner")
            .put(22, "Zuus")
            .put(23, "Kunkka")
            .put(25, "Lina")
            .put(26, "Lion")
            .put(27, "ShadowShaman")
            .put(28, "Slardar")
            .put(29, "Tidehunter")
            .put(30, "WitchDoctor")
            .put(31, "Lich")
            .put(32, "Riki")
            .put(33, "Enigma")
            .put(34, "Tinker")
            .put(35, "Sniper")
            .put(36, "Necrolyte")
            .put(37, "Warlock")
            .put(38, "Beastmaster")
            .put(39, "QueenOfPain")
            .put(40, "Venomancer")
            .put(41, "FacelessVoid")
            .put(42, "SkeletonKing")
            .put(43, "DeathProphet")
            .put(44, "PhantomAssassin")
            .put(45, "Pugna")
            .put(46, "TemplarAssassin")
            .put(47, "Viper")
            .put(48, "Luna")
            .put(49, "DragonKnight")
            .put(50, "Dazzle")
            .put(51, "Rattletrap")
            .put(52, "Leshrac")
            .put(53, "Furion")
            .put(54, "Life_Stealer")
            .put(55, "DarkSeer")
            .put(56, "Clinkz")
            .put(57, "Omniknight")
            .put(58, "Enchantress")
            .put(59, "Huskar")
            .put(60, "NightStalker")
            .put(61, "Broodmother")
            .put(62, "BountyHunter")
            .put(63, "Weaver")
            .put(64, "Jakiro")
            .put(65, "Batrider")
            .put(66, "Chen")
            .put(67, "Spectre")
            .put(68, "AncientApparition")
            .put(69, "DoomBringer")
            .put(70, "Ursa")
            .put(71, "SpiritBreaker")
            .put(72, "Gyrocopter")
            .put(73, "Alchemist")
            .put(74, "Invoker")
            .put(75, "Silencer")
            .put(76, "Obsidian_Destroyer")
            .put(77, "Lycan")
            .put(78, "Brewmaster")
            .put(79, "Shadow_Demon")
            .put(80, "LoneDruid")
            .put(81, "ChaosKnight")
            .put(82, "Meepo")
            .put(83, "Treant")
            .put(84, "Ogre_Magi")
            .put(85, "Undying")
            .put(86, "Rubick")
            .put(87, "Disruptor")
            .put(88, "Nyx_Assassin")
            .put(89, "Naga_Siren")
            .put(90, "KeeperOfTheLight")
            .put(91, "Wisp")
            .put(92, "Visage")
            .put(93, "Slark")
            .put(94, "Medusa")
            .put(95, "TrollWarlord")
            .put(96, "Centaur")
            .put(97, "Magnataur")
            .put(98, "Shredder")
            .put(99, "Bristleback")
            .put(100, "Tusk")
            .put(101, "Skywrath_Mage")
            .put(102, "Abaddon")
            .put(103, "Elder_Titan")
            .put(104, "Legion_Commander")
            .put(106, "Ember Spirit")
            .put(107, "Earth Spirit")
            .put(108, "Abyssal Underlord")
            .build();

}
